services:
    _defaults:
        autoconfigure: true

    Agonyz\ContaoCountdownBundle\Controller\CountdownController:
        tags:
            -
                name: contao.content_element
                category: miscellaneous
                template: ce_countdown
                type: countdown
